/*rename schema public to layer*/
alter table public.critical_biodiversity_areas_2019 set schema layer;
alter table public.erf set schema layer;
alter table public.critical_biodiversity_areas_2019_midscale set schema layer;
alter table public.critical_biodiversity_areas_2019_small_scale  set schema layer;
alter table public.dws_dams_50k set schema layer;
alter table public.ecosystems set schema layer;
alter table public.ecosystems_midscale set schema layer;
alter table public.ecosystems_small_scale set schema layer;
alter table public.farm_portion set schema layer;
alter table public.holding set schema layer;
alter table public.major_dws_dams_50k  set schema layer;
alter table public.major_rivers2018 set schema layer;
alter table public.midscale_dws_dams_50k set schema layer;
alter table public.midscale_zaf_roads set schema layer;
alter table public.parent_farm set schema layer;
alter table public.place_name_larger_scale set schema layer;
alter table public.place_name_largest_scale set schema layer;
alter table public.place_name_midscale set schema layer;
alter table public.place_name_smallest_scale set schema layer;
alter table public.protected_areas_2022 set schema layer;
alter table public.protected_areas_2022_midscale set schema layer;
alter table public.protected_areas_2022_small_scale set schema layer;
alter table public.rivers2018 set schema layer;
alter table public.world set schema layer;
alter table public.zaf_boundary set schema layer;
alter table public.zaf_boundary_small_scale set schema layer;
alter table public.zaf_highways set schema layer;
alter table public.zaf_provinces_small_scale set schema layer;
alter table public.zaf_public_places set schema layer;
alter table public.zaf_public_places_midscale set schema layer;
alter table public.zaf_roads set schema layer;

/*rename id to cname for erf,  holding, farm_portion, parent_farm*/
ALTER TABLE layer.erf RENAME COLUMN id TO cname;
ALTER TABLE layer.farm_portion RENAME COLUMN id TO cname;
ALTER TABLE layer.holding RENAME COLUMN id TO cname;
ALTER TABLE layer.parent_farm RENAME COLUMN id TO cname;
/*rename fid to id*/
alter table layer.critical_biodiversity_areas_2019 RENAME COLUMN fid TO id;
alter table layer.erf RENAME COLUMN fid TO id;
alter table layer.critical_biodiversity_areas_2019_midscale RENAME COLUMN fid TO id;
alter table layer.critical_biodiversity_areas_2019_small_scale  RENAME COLUMN fid TO id;
alter table layer.dws_dams_50k RENAME COLUMN fid TO id;
alter table layer.ecosystems RENAME COLUMN fid TO id;
alter table layer.ecosystems_midscale RENAME COLUMN fid TO id;
alter table layer.ecosystems_small_scale RENAME COLUMN fid TO id;
alter table layer.farm_portion RENAME COLUMN fid TO id;
alter table layer.holding RENAME COLUMN fid TO id;
alter table layer.major_dws_dams_50k  RENAME COLUMN fid TO id;
alter table layer.major_rivers2018 RENAME COLUMN fid TO id;
alter table layer.midscale_dws_dams_50k RENAME COLUMN fid TO id;
alter table layer.midscale_zaf_roads RENAME COLUMN fid TO id;
alter table layer.parent_farm RENAME COLUMN fid TO id;
alter table layer.place_name_larger_scale RENAME COLUMN fid TO id;
alter table layer.place_name_largest_scale RENAME COLUMN fid TO id;
alter table layer.place_name_midscale RENAME COLUMN fid TO id;
alter table layer.place_name_smallest_scale RENAME COLUMN fid TO id;
alter table layer.protected_areas_2022 RENAME COLUMN fid TO id;
alter table layer.protected_areas_2022_midscale RENAME COLUMN fid TO id;
alter table layer.protected_areas_2022_small_scale RENAME COLUMN fid TO id;
alter table layer.rivers2018 RENAME COLUMN fid TO id;
alter table layer.world RENAME COLUMN fid TO id;
alter table layer.zaf_boundary RENAME COLUMN fid TO id;
alter table layer.zaf_boundary_small_scale RENAME COLUMN fid TO id;
alter table layer.zaf_highways RENAME COLUMN fid TO id;
alter table layer.zaf_provinces_small_scale RENAME COLUMN fid TO id;
alter table layer.zaf_public_places RENAME COLUMN fid TO id;
alter table layer.zaf_public_places_midscale RENAME COLUMN fid TO id;
alter table layer.zaf_roads RENAME COLUMN fid TO id;